"""empty message

Revision ID: 642dd0ad1920
Revises: 3e69470e62e8
Create Date: 2018-04-17 15:42:01.018702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642dd0ad1920'
down_revision = '3e69470e62e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_confirmed')
    # ### end Alembic commands ###
